site_name: Citrix HTML5 Receiver SDK
site_description: Reference guide for Citrix HTML5 Receiver SDK
theme_dir: citrix-sdk
markdown_extensions:
  - admonition
  - codehilite
  - toc:
     anchorlink: True

pages:
- HDX SDK for HTML5: index.md
- SDK Capabilities: capabilities.md
- API Reference:
  - Class:
    - ReceiverError: ReceiverError.md
    - Session: session.md
  - Namespaces: 
    - Receiver: citrix-receiver.md
  - Global: global.md
- SDK Sample: sample.md
